### ISSUE TITLE
Compound goals data

### ISSUE THREAD

**Issue by etaoxing** [google-research/relay-policy-learning#1]
The demo data seems to be separated into different tasks. Were the VR demo users given a desired goal for each task, and is this goal data available?

**Comment by vikashplus** [comment]
To ensure that the data distribution is uniform across various elements in the scene, users were given general guidelines for which subset of elements to interact with. A random subset was selected for each new interaction session. The data from all the sessions were merged together (without any session metadata) to ensure interaction uniformity and session anonymity.

**Comment by etaoxing** [comment]
Ok thanks! It seems like [d4rl](https://github.com/rail-berkeley/d4rl/blob/9b1eeab56d2adc5afa0541b6dd95399de9635390/d4rl/kitchen/kitchen_envs.py#L9) has integrated the environment with the object goals.
